DROP DATABASE LINK "DB_CC1";
/
CREATE DATABASE LINK "DB_CC1"
CONNECT TO cc1
IDENTIFIED BY oracle
USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))(CONNECT_DATA = (SID = orcl)))'
/
DROP DATABASE LINK "DB_CC2";
/
CREATE DATABASE LINK "DB_CC2"
CONNECT TO cc2
IDENTIFIED BY oracle
USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))(CONNECT_DATA = (SID = orcl)))'