DROP DATABASE LINK "DB_CB";
/
CREATE DATABASE LINK "DB_CB"
CONNECT TO cb
IDENTIFIED BY oracle
USING '(DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521)))(CONNECT_DATA = (SID = orcl)))'