drop sequence "SEQ_ID_CAST";
drop sequence "SEQ_ID_COPIE";
drop sequence "SEQ_ID_STUDIO";
/
CREATE SEQUENCE SEQ_ID_CAST INCREMENT BY 1 START WITH 0 MINVALUE 0 MAXVALUE 99999999 ORDER;
CREATE SEQUENCE SEQ_ID_COPIE INCREMENT BY 1 START WITH 0 MINVALUE 0 MAXVALUE 99999999 ORDER;
CREATE SEQUENCE SEQ_ID_STUDIO INCREMENT BY 1 START WITH 0 MINVALUE 0 MAXVALUE 99999999 ORDER;