ALTER SESSION SET PLSCOPE_SETTINGS = 'IDENTIFIERS:NONE';
CREATE USER CB IDENTIFIED BY oracle ;

-- ROLES
GRANT "RESOURCE" TO CB ;
GRANT "CONNECT" TO CB ;

-- SYSTEM PRIVILEGES
GRANT CREATE SEQUENCE TO CB ;
GRANT CREATE JOB TO CB ;
GRANT CREATE SYNONYM TO CB ;
GRANT CREATE TYPE TO CB ;
GRANT CREATE DATABASE LINK TO CB ;
GRANT CREATE VIEW TO CB ;
GRANT DROP ANY MATERIALIZED VIEW TO CB ;
GRANT CREATE MATERIALIZED VIEW TO CB ;
GRANT ON COMMIT REFRESH TO CB;
GRANT execute ON dbms_lock TO CB;
GRANT CREATE TABLE TO CB;




CREATE USER CC1 IDENTIFIED BY oracle ;

-- ROLES
GRANT "RESOURCE" TO CC1 ;
GRANT "CONNECT" TO CC1 ;

-- SYSTEM PRIVILEGES
GRANT CREATE SEQUENCE TO CC1 ;
GRANT CREATE JOB TO CC1 ;
GRANT CREATE SYNONYM TO CC1 ;
GRANT CREATE TYPE TO CC1 ;
GRANT CREATE DATABASE LINK TO CC1 ;
GRANT CREATE VIEW TO CC1 ;
GRANT DROP ANY MATERIALIZED VIEW TO CC1 ;
GRANT CREATE MATERIALIZED VIEW TO CC1 ;
GRANT ON COMMIT REFRESH TO CC1;
GRANT execute ON dbms_lock TO CC1;
GRANT CREATE TABLE TO CC1;




CREATE USER CC2 IDENTIFIED BY oracle ;

-- ROLES
GRANT "RESOURCE" TO CC2 ;
GRANT "CONNECT" TO CC2 ;

-- SYSTEM PRIVILEGES
GRANT CREATE SEQUENCE TO CC2 ;
GRANT CREATE JOB TO CC2 ;
GRANT CREATE SYNONYM TO CC2 ;
GRANT CREATE TYPE TO CC2 ;
GRANT CREATE DATABASE LINK TO CC2 ;
GRANT CREATE VIEW TO CC2 ;
GRANT DROP ANY MATERIALIZED VIEW TO CC2 ;
GRANT CREATE MATERIALIZED VIEW TO CC2 ;
GRANT ON COMMIT REFRESH TO CC2;
GRANT execute ON dbms_lock TO CC2;
GRANT CREATE TABLE TO CC2;




CREATE USER MK IDENTIFIED BY oracle ;

-- ROLES
GRANT "RESOURCE" TO MK ;
GRANT "CONNECT" TO MK ;

-- SYSTEM PRIVILEGES
GRANT CREATE SEQUENCE TO MK ;
GRANT CREATE JOB TO MK ;
GRANT CREATE SYNONYM TO MK ;
GRANT CREATE TYPE TO MK ;
GRANT CREATE DATABASE LINK TO MK ;
GRANT CREATE VIEW TO MK ;
GRANT DROP ANY MATERIALIZED VIEW TO MK ;
GRANT CREATE MATERIALIZED VIEW TO MK ;
GRANT ON COMMIT REFRESH TO MK;
GRANT execute ON dbms_lock TO MK;
GRANT CREATE TABLE TO MK;